services:
  - type: web
    name: helix-jsdom
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html